import type { Insight } from "./insights";

// Naturally rewritten Traditional Chinese versions of each English insight,
// targeted at Vancouver / Richmond Chinese-speaking dental patients.
export const INSIGHTS_ZH: Insight[] = [
  {
    slug: "all-on-4-vs-traditional-implants",
    title: "All-on-4 與傳統植牙怎麼選？溫哥華患者完整比較指南",
    excerpt: "從療程時間、骨量需求、費用到生活品質，完整比較 All-on-4 全口重建與傳統單顆植牙，協助您與牙醫師一同做出最適合的選擇。",
    category: "植牙",
    readMin: 8,
    image: "/featured/all-on-4.jpg",
    date: "2026-04-12",
    body: [
      { paragraphs: ["當您面臨多顆缺牙的問題，現代牙科主要提供兩條路徑：以四支植體完成的 All-on-4 全口重建，或一顆缺牙搭配一支植體的傳統單顆植牙。兩者都能帶來穩定、近似真牙的咀嚼體驗，但治療方式與適用對象大不相同。"] },
      { heading: "什麼是 All-on-4 全口重建？", paragraphs: ["All-on-4 是以四支策略性植入的植體，支撐整排上顎或下顎牙齒的全口重建方案。後牙區域的植體採傾斜植入設計，目的在於最大化與骨頭的接觸面積，並降低補骨手術的需求。"] },
      { heading: "什麼是傳統單顆植牙？", paragraphs: ["傳統植牙是針對每顆缺牙植入一支鈦金屬植體（或以一至兩支植體支撐小範圍的牙橋）。當您僅缺少一至幾顆牙齒、骨頭條件良好時，這仍是長期穩定的黃金標準。"] },
      { heading: "兩種方案的核心差異", list: [
        "植體數量：All-on-4 每顎使用 4 支植體；傳統植牙每顆缺牙約需 1 支，整排重建可能需要 6–8 支以上。",
        "療程時間：All-on-4 通常可於手術當日裝戴固定式臨時假牙；傳統植牙每顆需數月骨整合時間。",
        "骨量需求：All-on-4 透過後牙傾斜植入，常可避免大範圍補骨；傳統植牙較常需要先補骨。",
        "整體費用：單顆植牙費用較低，但若整排重建，All-on-4 通常比逐顆重建更具成本效益。",
        "後續維護：兩種方案都需要良好的居家清潔與定期回診洗牙。",
      ]},
      { heading: "哪些病患特別適合 All-on-4？", paragraphs: ["若整排牙齒大多缺失，或剩餘牙齒長期預後不佳，All-on-4 通常是更合適的選擇。傳統植牙則適合僅缺少少數牙齒、整體咬合穩定的情況。"] },
      { heading: "術後恢復怎麼預期？", paragraphs: ["多數 All-on-4 病患手術當日即裝戴固定式臨時假牙，約一週內可逐步恢復軟質飲食。單顆植牙則通常需 3–6 個月骨整合後，再裝戴正式牙冠。"] },
    ],
    faqs: [
      { q: "All-on-4 是永久性的嗎？", a: "植體本身設計為長期使用；上方的假牙在多年使用後可能依需求更新。" },
      { q: "All-on-4 有可能失敗嗎？", a: "植體失敗雖少見但仍有可能，吸菸、控制不佳的糖尿病與居家清潔不良是主要風險因子。" },
    ],
    related: ["x-guide-implant-accuracy", "implant-vs-bridge"],
  },
  {
    slug: "what-to-expect-during-invisalign",
    title: "Invisalign 隱形矯正全程體驗：時程、附件與成果完整解析",
    excerpt: "從第一次數位掃描到配戴維持器，帶您完整了解 Invisalign 隱形矯正的療程節奏、黏附件設計與如何讓矯正成果更穩定。",
    category: "Invisalign 隱形矯正",
    readMin: 7,
    image: "/featured/invisalign.jpg",
    date: "2026-03-28",
    body: [
      { paragraphs: ["Invisalign 隱適美已成為傳統金屬矯正最受歡迎的隱形替代方案。但實際的療程，每週究竟會經歷什麼？"] },
      { heading: "第一步｜數位口掃與 ClinCheck 模擬", paragraphs: ["透過口內 3D 掃描，我們會建構您的數位牙齒模型，並完整規劃所有牙齒移動路徑。療程開始前，您就能預覽矯正完成的微笑樣貌。"] },
      { heading: "第二步｜黏附件 (Attachments)", paragraphs: ["多數個案會在特定牙齒上黏貼與牙齒同色的小型附件，提供牙套精準施力的支點，協助完成單純牙套較難達成的旋轉與壓出動作。"] },
      { heading: "第三步｜配戴牙套", paragraphs: ["每副牙套每天需配戴 20–22 小時，通常每 7–10 天更換一副。僅於用餐、飲用清水以外的飲品與刷牙時取下。"] },
      { heading: "第四步｜微調 (Refinement)", paragraphs: ["當初次牙套即將結束，我們會再次數位掃描，安排短期的微調牙套，將細節調整到最佳狀態。"] },
      { heading: "第五步｜維持器", paragraphs: ["矯正完成不代表結束。長期穩定配戴維持器（通常為夜間配戴），能保護您的矯正成果不再位移。"] },
    ],
    faqs: [
      { q: "Invisalign 一般要矯正多久？", a: "依個案複雜度，多數療程於 6–18 個月內完成。" },
      { q: "戴牙套會不會口齒不清？", a: "部分病患在前幾天會稍有適應期，通常很快就能恢復自然發音。" },
    ],
    related: ["choose-cosmetic-dentist-vancouver"],
  },
  {
    slug: "x-guide-implant-accuracy",
    title: "X-Guide 即時 3D 導航如何提升植牙精準度？",
    excerpt: "X-Guide 為植牙手術帶來如同 GPS 的即時 3D 導航，從定位、安全性到美學成果，全面提升現代植牙的可預測性。",
    category: "技術與設備",
    readMin: 6,
    image: "/featured/x-guide.jpg",
    date: "2026-03-10",
    body: [
      { paragraphs: ["過去的植牙手術，外科醫師主要倚賴經驗判斷與 2D X 光影像進行徒手植入。X-Guide 在此基礎上加入即時 3D 導航——可說是植牙專用的 GPS。"] },
      { heading: "X-Guide 是怎麼運作的？", paragraphs: ["術前先透過 CBCT 數位影像規劃植體的精確位置；手術時，X-Guide 系統會即時追蹤手機位置，並將位置疊加至 3D 規劃影像上，提供毫米級的視覺回饋。"] },
      { heading: "為什麼精準度這麼重要？", list: [
        "美學表現更佳：植體可精準位於未來牙冠的理想位置。",
        "安全避開神經、鼻竇等重要結構。",
        "手術切口更小、創傷更輕。",
        "癒合更快，後續贗復設計也更具可預測性。",
      ]},
      { heading: "哪些病患特別受惠？", paragraphs: ["接受多顆植牙、前牙美學區植牙、全口重建或骨量條件較有限的病患，從導引式手術獲得的好處最為顯著。"] },
    ],
    related: ["all-on-4-vs-traditional-implants", "benefits-of-digital-dentistry"],
  },
  {
    slug: "benefits-of-digital-dentistry",
    title: "現代病患為什麼受惠於數位牙科？",
    excerpt: "從口內掃描到 3D 列印贗復，數位牙科正悄悄改變病患的看診體驗，讓治療更精準、更舒適、更可預測。",
    category: "技術與設備",
    readMin: 6,
    image: "/equipment/tech-cbct.jpg",
    date: "2026-02-22",
    body: [
      { paragraphs: ["數位牙科正在以更精準、視覺化的流程取代許多傳統的不適體驗——包括取模印膏、反覆測試與多次回診。"] },
      { heading: "口內 3D 掃描", paragraphs: ["小型掃描頭幾分鐘內即可建構完整的口腔 3D 模型，免去托盤與作嘔反射，準確度也明顯更高。"] },
      { heading: "3D CBCT 影像", paragraphs: ["錐狀束電腦斷層 (CBCT) 讓我們能在手術前以三維方式檢視齒槽骨、神經與鼻竇結構。"] },
      { heading: "導引式手術", paragraphs: ["以軟體完成的數位治療規劃，可透過手術導板或 X-Guide 即時導航，精準執行於口腔中。"] },
      { heading: "病患會感受到的差異", list: [
        "看診時間更短、過程更舒適。",
        "重做與修改的次數明顯減少。",
        "治療結果可在開始前先行預覽。",
      ]},
    ],
    related: ["x-guide-implant-accuracy"],
  },
  {
    slug: "implant-vs-bridge",
    title: "缺一顆牙，植牙與牙橋哪個比較好？",
    excerpt: "兩者都能恢復咀嚼功能，但長期表現截然不同。本文帶您一次理解單顆植牙與固定式牙橋的差異。",
    category: "植牙",
    readMin: 5,
    image: "/featured/dental-implants.jpg",
    date: "2026-02-05",
    body: [
      { paragraphs: ["當您僅缺少一顆牙時，牙醫師通常會提出兩種選項：單顆植牙或傳統的固定式牙橋。兩者都能恢復咀嚼功能，但長期表現大不相同。"] },
      { heading: "牙橋是怎麼做的？", paragraphs: ["醫師會將缺牙兩側的鄰牙修磨成牙冠形狀，再以連接式的牙冠與中間的假牙橋接，整個療程通常於數週內完成。"] },
      { heading: "植牙是怎麼做的？", paragraphs: ["醫師將鈦金屬植體植入齒槽骨中，待數月骨整合完成後，於上方裝戴單顆牙冠——完全不需要動到鄰牙。"] },
      { heading: "為什麼長期通常植牙較佔優勢？", list: [
        "鄰近健康牙齒不需修磨。",
        "透過植體刺激，有助於保留齒槽骨。",
        "可正常使用牙線清潔，居家照護更容易。",
        "使用壽命通常顯著長於牙橋。",
      ]},
      { heading: "什麼時候牙橋仍是合適選擇？", paragraphs: ["當鄰牙原本就需要做牙冠、骨量嚴重不足且不接受補骨，或療程時間是優先考量時，牙橋仍可能是合適的選項。"] },
    ],
    related: ["all-on-4-vs-traditional-implants"],
  },
  {
    slug: "choose-cosmetic-dentist-vancouver",
    title: "如何在溫哥華選擇值得信賴的美學牙醫？",
    excerpt: "美學牙科兼具藝術與精密工程。本文整理在溫哥華地區尋找美學牙科診所時，最值得關注的五個面向。",
    category: "美學牙科",
    readMin: 6,
    image: "/featured/cosmetics.jpg",
    date: "2026-01-18",
    body: [
      { paragraphs: ["美學牙科是您能投資在自己身上、最具個人色彩的選擇之一。在溫哥華選擇美學牙醫時，以下五個面向值得仔細評估。"] },
      { heading: "1. 是否採用數位流程", paragraphs: ["現代化的美學牙科診所應提供數位微笑設計、口內 3D 掃描，並能在治療前清楚預覽預期成果。"] },
      { heading: "2. 治療技術是否多元", paragraphs: ["陶瓷貼片、Bioclear、顯微鏡牙科與矯正治療各有適用情境。理想的醫師會優先建議最保守、最符合您目標的方案。"] },
      { heading: "3. 是否有完整案例可參考", paragraphs: ["請務必看看與您年齡、牙齒形狀與複雜度相近的真實案例，更能評估醫師的風格與經驗。"] },
      { heading: "4. 是否提供完整後續照護", paragraphs: ["請確認同一間診所是否能持續提供洗牙、修復與其他長期照護，不只負責美學療程本身。"] },
      { heading: "5. 諮詢的方式是否真誠", paragraphs: ["優質的診所會先傾聽您的期待，再提出建議；而不是反過來推銷療程。"] },
    ],
    related: ["what-to-expect-during-invisalign", "benefits-of-digital-dentistry"],
  },
];
