import type { ServiceItem, Doctor } from "./site";

export const SITE_ZH = {
  name: "U-Dental 牙醫診所",
  phone: "604-423-3839",
  phoneHref: "tel:+16044233839",
  email: "info@u-dental.ca",
  emailHref: "mailto:info@u-dental.ca",
  address: "溫哥華 Kitsilano West Broadway 2933 號",
  area: "溫哥華 Kitsilano",
  hours: [
    { d: "週一至週三", t: "9:30am – 5:30pm" },
    { d: "週四", t: "休診" },
    { d: "週五", t: "9:30am – 5:30pm" },
    { d: "週六", t: "9am – 5pm" },
    { d: "週日", t: "休診" },
  ],
} as const;

export const SERVICE_CATEGORIES_ZH = {
  advanced: "進階治療",
  cosmetic: "美學與矯正牙科",
  general: "一般牙科",
  replacement: "缺牙重建",
} as const;

export const SERVICES_ZH: ServiceItem[] = [
  {
    slug: "dental-implants",
    name: "植牙 (人工植牙)",
    short: "結合 3D 數位導航的高精準度植牙治療，重現自然咬合與美觀。",
    category: "replacement",
    image: "/services/dental-implants.png",
    intro: "植牙是長期解決缺牙問題的成熟方案，能同時恢復咀嚼功能與牙齒外觀。U-Dental 採用全數位流程進行植牙規劃，提升精準度並減少不適。",
    benefits: ["外觀自然、貼近真牙", "恢復咬合與咀嚼功能", "全程數位規劃，定位精準", "有助於保留齒槽骨與鄰牙健康"],
    when: ["單顆或多顆缺牙", "活動假牙鬆動或不適", "希望尋求長期穩定的缺牙解決方案"],
    tech: "結合術前數位影像規劃與 X-Guide 即時 3D 導航，協助醫師於手術中精準定位。",
  },
  {
    slug: "all-on-4",
    name: "All-on-4 全口重建",
    short: "以四支植體重建整排牙齒，讓全口重建一次到位。",
    category: "replacement",
    image: "/services/all-on-4.png",
    intro: "All-on-4 全口重建以四支策略性植入的植體，支撐整排上顎或下顎假牙，是傳統活動假牙之外更穩固的選擇。",
    benefits: ["整排固定式假牙，咀嚼穩定", "多數情況下可避免大範圍補骨", "外觀與真牙自然相近", "顯著提升生活品質"],
    when: ["整排或大範圍缺牙", "活動假牙穩定度不佳", "希望一次完成全口重建"],
    tech: "全程採用數位規劃與導引手術流程，提升整體精準度與安全性。",
  },
  {
    slug: "invisalign",
    name: "Invisalign 隱適美隱形矯正",
    short: "舒適、可拆卸的隱形牙套，悄悄完成牙齒矯正。",
    category: "cosmetic",
    image: "/featured/invisalign.jpg",
    intro: "Invisalign 隱適美透過一系列量身訂製的透明牙套，溫和地將牙齒移動到理想位置，是傳統金屬矯正器之外更美觀的選擇。",
    benefits: ["透明美觀，社交無負擔", "可自行取下，方便潔牙與用餐", "舒適度高，異物感低", "全程數位掃描規劃"],
    when: ["牙齒擁擠或排列不整", "牙縫過大", "輕至中度咬合異常"],
    tech: "以口內 3D 數位掃描與 ClinCheck 模擬軟體，事前預覽矯正後的微笑。",
  },
  {
    slug: "orthodontics",
    name: "齒列矯正",
    short: "運用現代矯正技術，改善齒列與咬合關係。",
    category: "cosmetic",
    image: "/services/orthodontics.png",
    intro: "齒列矯正治療專注於改善上下顎咬合與牙齒排列，提升美觀與長期口腔健康。",
    benefits: ["改善咬合與排列", "更易維持口腔清潔", "依個案量身規劃療程"],
    when: ["牙齒擁擠", "牙縫過大", "咬合不正"],
  },
  {
    slug: "x-guide-real-time-3d-guidance-surgery",
    name: "X-Guide 即時 3D 導航植牙手術",
    short: "如同植牙的 GPS 導航，提供術中即時 3D 視覺定位。",
    category: "advanced",
    image: "/services/x-guide.png",
    intro: "X-Guide 是植牙手術中的即時 3D 導航系統，能讓醫師在術中以毫米級精度確認植體位置，大幅提升手術可預測性。",
    benefits: ["術中即時 3D 導航", "提升植體定位精準度", "支援更安全可控的手術流程"],
    when: ["接受植牙手術的病患", "需要高度精準度的複雜植牙個案"],
    tech: "結合術前 CBCT 數位規劃與術中即時導航回饋。",
  },
  {
    slug: "oral-surgery",
    name: "口腔外科手術",
    short: "在獨立手術室中提供高規格的口腔顎面外科治療。",
    category: "advanced",
    image: "/services/oral-surgery.png",
    intro: "U-Dental 設有獨立手術室，採醫療中心等級的無菌標準，能因應各類口腔外科手術需求。",
    benefits: ["獨立專屬手術室", "重視病患舒適與安全", "現代化手術流程設計"],
    when: ["複雜拔牙", "植牙相關手術", "其他口腔外科需求"],
  },
  {
    slug: "wisdom-tooth-extraction",
    name: "智齒拔除",
    short: "以舒適、安全為核心的智齒拔除療程。",
    category: "advanced",
    image: "/services/wisdom-tooth.png",
    intro: "智齒生長空間不足時，常造成不適、推擠鄰牙或反覆發炎。我們的醫師團隊擁有豐富智齒拔除經驗，協助您安心完成療程。",
    benefits: ["舒緩擁擠與壓迫不適", "重視術後恢復體驗", "現代化手術環境"],
    when: ["後牙區域疼痛或腫脹", "智齒水平阻生", "反覆智齒發炎"],
  },
  {
    slug: "cosmetics-and-comprehensive-dentistry",
    name: "美學牙科與全方位牙科治療",
    short: "結合數位微笑設計與全口治療規劃，重塑自信微笑。",
    category: "cosmetic",
    image: "/services/cosmetics.png",
    intro: "美學與全方位牙科治療結合美觀與功能，依數位流程整合微笑設計、修復與矯正等多項治療規劃。",
    benefits: ["數位微笑設計", "整合式治療規劃", "兼顧美觀與咬合功能"],
    when: ["希望改善整體微笑外觀", "多項治療需要整合", "重視長期治療規劃"],
  },
  {
    slug: "dental-cleaning",
    name: "專業洗牙與牙周保健",
    short: "預防勝於治療，維護健康牙齦與口腔環境。",
    category: "general",
    image: "/services/dental-cleaning.png",
    intro: "定期專業洗牙能有效去除日常潔牙難以清除的牙菌斑與牙結石，是維護牙齦健康與口腔長期穩定的基礎。",
    benefits: ["維護牙齦健康", "去除牙菌斑與結石", "及早發現潛在問題"],
    when: ["定期口腔保健", "牙齦健康狀況需追蹤"],
  },
  {
    slug: "emergency",
    name: "牙科急診",
    short: "在最需要的時候，提供即時的牙科緊急處理。",
    category: "general",
    image: "/services/emergency.png",
    intro: "牙科緊急狀況可能突然發生，請立即與診所聯繫，我們將儘快安排處理。",
    benefits: ["即時評估與處置", "專注於止痛與穩定", "規劃後續完整治療"],
    when: ["突發性劇烈牙痛", "牙齒外傷或斷裂", "假牙、補綴物脫落"],
  },
  {
    slug: "restorations",
    name: "牙齒修復",
    short: "以現代修復技術重建受損牙齒的美觀與功能。",
    category: "general",
    image: "/services/restorations.png",
    intro: "牙齒修復可協助處理蛀牙、磨耗或外傷造成的損傷，恢復牙齒的功能與外觀。",
    benefits: ["恢復咀嚼功能", "選用同色樹脂等美觀材料", "支持長期口腔健康"],
    when: ["蛀牙", "牙齒磨耗或缺損", "更換老舊填補物"],
  },
  {
    slug: "crown-and-bridges",
    name: "牙冠與牙橋",
    short: "重建受損牙齒結構或修復缺牙。",
    category: "general",
    image: "/services/crown-bridges.png",
    intro: "牙冠與牙橋以自然外觀的材質，重建嚴重受損或缺失的牙齒結構，恢復咬合與美觀。",
    benefits: ["重建牙齒結構與強度", "牙橋可修復缺牙區域", "兼顧美觀與功能"],
    when: ["牙齒嚴重損傷", "根管治療後保護牙齒", "需要固定式缺牙修復"],
  },
  {
    slug: "root-canal-treatment",
    name: "根管治療",
    short: "保留自然牙、處理牙髓感染的精細治療。",
    category: "general",
    image: "/services/root-canal.png",
    intro: "當牙齒內部牙髓組織受到感染或損傷，根管治療能協助保留自然牙，避免拔除。",
    benefits: ["協助保留自然牙", "重視治療過程舒適度", "採用現代根管治療技術"],
    when: ["劇烈或持續性牙痛", "對冷熱敏感久未消退", "深層蛀牙或外傷"],
  },
  {
    slug: "denture",
    name: "活動假牙",
    short: "為多顆缺牙提供舒適、合身的可拆卸假牙方案。",
    category: "replacement",
    image: "/services/denture.png",
    intro: "活動假牙是替代多顆缺牙與相鄰軟組織的可拆卸式義齒，能恢復外觀與基本口腔功能。",
    benefits: ["恢復咀嚼與發音功能", "依口腔狀況量身製作", "外觀自然"],
    when: ["多顆缺牙", "希望採用可拆卸方案"],
  },
  {
    slug: "microscopic-dentistry",
    name: "顯微鏡精密牙科治療",
    short: "在高倍顯微鏡下進行精細的修復與根管治療。",
    category: "advanced",
    image: "/services/microscopic-dentistry.png",
    intro: "顯微鏡牙科以高倍視野放大治療部位，協助醫師於修復、根管與美學治療中達到極高的精準度。",
    benefits: ["顯著提升視覺精準度", "更保守的牙齒磨除", "提升治療可預測性"],
    when: ["精細修復治療", "根管治療", "美學細節調整"],
    tech: "採用 Leica M320D 牙科顯微鏡。",
  },
  {
    slug: "bioclear",
    name: "Bioclear 美學樹脂修復",
    short: "以透明矩陣與流動樹脂技術，自然關閉黑三角。",
    category: "cosmetic",
    image: "/services/bioclear.png",
    intro: "Bioclear 是現代化注射式樹脂修復技術，運用透明矩陣與加溫流動樹脂，能微創地關閉牙縫黑三角並重建牙齒外觀。",
    benefits: ["有效關閉黑三角", "微創、保留自然齒質", "外觀自然且耐用"],
    when: ["牙齒間出現黑三角", "牙齒磨耗或缺角", "希望以微創方式改善美觀"],
  },
  {
    slug: "galvosurge-for-peri-implantitis-treatment",
    name: "GalvoSurge 植體周圍炎治療",
    short: "以電解技術清潔植體表面，協助維護植體長期健康。",
    category: "advanced",
    image: "/services/galvosurge.png",
    intro: "GalvoSurge 是進階電解清潔系統，能精準去除植體表面的生物膜，協助維持植體周圍組織健康。",
    benefits: ["精準去除生物膜", "支援植體長期穩定", "微創式治療流程"],
    when: ["植體周圍炎", "植體周圍組織發炎", "植體長期維護"],
  },
  {
    slug: "botox",
    name: "Botox 醫療美容",
    short: "於牙科臨床環境下，提供專業的肉毒桿菌療程。",
    category: "cosmetic",
    image: "/services/botox.png",
    intro: "Botox 療程可於牙科臨床情境下提供，依個別狀況評估適用性，歡迎與我們的團隊進一步討論。",
    benefits: ["於專業臨床環境進行", "個人化評估"],
    when: ["希望了解相關臨床治療選項的病患"],
  },
];

export const FEATURED_TREATMENTS_ZH = [
  { slug: "dental-implants", title: "植牙 (人工植牙)", image: "/featured/dental-implants.jpg", tagline: "全程數位規劃，毫米級精準植入。" },
  { slug: "cosmetics-and-comprehensive-dentistry", title: "美學牙科", image: "/featured/cosmetics.jpg", tagline: "以數位流程設計理想微笑。" },
  { slug: "invisalign", title: "Invisalign 隱形矯正", image: "/featured/invisalign.jpg", tagline: "量身訂製的隱形牙套。" },
  { slug: "x-guide-real-time-3d-guidance-surgery", title: "X-Guide 導航植牙", image: "/featured/x-guide.jpg", tagline: "即時 3D 導航的精準手術。" },
  { slug: "all-on-4", title: "All-on-4 全口重建", image: "/featured/all-on-4.jpg", tagline: "一次完成整排重建。" },
];

export const DOCTORS_ZH: Doctor[] = [
  {
    slug: "dr-joyce-wu",
    name: "吳醫師 Dr. Joyce Wu",
    credentials: "DDS",
    photo: "https://u-dental.ca/wp-content/uploads/2018/12/Dr.-Joyce-Wu-3.jpg",
    specialties: ["一般牙科", "齒列矯正與 Invisalign", "Botox"],
    summary: "同時取得台灣與加拿大牙醫師執照，數十年來於溫哥華提供細膩、全方位的一般與矯正牙科照護。",
    bio: [
      "Dr. Joyce Wu 1992 年畢業於台北國立陽明醫學院，並於台北榮民總醫院完成一般牙科訓練。在台北榮總期間，她精進臨床牙科技術，並成為榮總牙科部的臨床指導醫師。",
      "1997 年移民加拿大後，Dr. Wu 通過加拿大國家牙醫師考試，成為少數同時擁有台、加兩地執照的牙醫師。多年來她以細膩的服務態度與紮實的臨床功力，在大溫哥華地區累積極佳的口碑。「Joyce Wu Dental」是許多病患在大溫地區心目中的首選，加入 U-Dental 後，她持續與團隊一起為病患提供高品質的綜合牙科照護。",
    ],
    related: ["orthodontics", "invisalign", "botox", "dental-cleaning"],
  },
  {
    slug: "dr-lo-lin-tsai",
    name: "蔡醫師 Dr. Lo-Lin Tsai",
    credentials: "DDS, M Sc, PhD",
    photo: "/doctors/lo-lin-tsai.webp",
    specialties: ["口腔顎面外科", "植牙", "智齒拔除"],
    summary: "口腔顎面外科專科醫師，累積超過 20,000 例智齒拔除與 5,000 例以上植牙手術經驗。",
    bio: [
      "Dr. Lo-Lin Tsai 2000 年自牙醫系畢業，於台灣頂尖醫學中心完成三年口腔顎面外科訓練，是當時台灣最年輕的口腔顎面外科專科醫師。多年來他持續精進，2014 年升任牙醫學系副教授，2017 年起擔任博士班指導教授。",
      "Dr. Tsai 以精湛的外科技術聞名，至今已執行超過 20,000 例智齒拔除與 5,000 例以上的植牙手術，並於 2012 年成為台灣 All-on-4 顴骨植體全口重建的先驅外科醫師。2015 年移民加拿大並通過國家牙醫師考試後，他持續以高水準的專業服務台、加兩地的病患。",
    ],
    related: ["oral-surgery", "dental-implants", "all-on-4", "wisdom-tooth-extraction"],
  },
  {
    slug: "dr-clair-wang",
    name: "王醫師 Dr. Claire Wang",
    credentials: "DDS",
    photo: "/doctors/clair-wang.webp",
    specialties: ["家庭牙科", "美學牙科", "贗復牙科", "Invisalign"],
    summary: "親切細膩的家庭牙醫，Invisalign 優選提供醫師，並具備舒眠鎮靜與雷射牙科認證。",
    bio: [
      "Dr. Claire Wang 為素富盛名的 Surrey「Just Smiles」診所主治醫師。她於 UBC 取得生化系榮譽學士學位，並於西安大略大學以院長榮譽榜佳績取得牙醫博士學位。",
      "Dr. Wang 提供各年齡層的家庭牙科服務，溫暖細膩的個人特質讓兒童與焦慮病患都能放鬆。她重視醫病之間的溝通，並持續精進專業，取得 World Clinical Laser Institute 雷射牙科準會員資格、舒眠鎮靜認證以及 Invisalign 優選提供醫師資格。她同時也是 UBC 牙醫學院的兼任臨床指導醫師。",
    ],
    related: ["cosmetics-and-comprehensive-dentistry", "invisalign", "crown-and-bridges", "dental-cleaning"],
  },
  {
    slug: "dr-edward-cheng",
    name: "鄭醫師 Dr. Edward Cheng",
    credentials: "DMD",
    photo: "/doctors/edward-cheng.webp",
    specialties: ["一般牙科", "牙科急診", "贗復牙科", "全身麻醉牙科治療"],
    summary: "UBC 畢業的家庭牙醫，以親切服務聞名，並擁有為焦慮與兒童病患進行全身麻醉牙科治療的豐富經驗。",
    bio: [
      "Dr. Edward Cheng 畢業於 UBC 牙醫學系，並於紐約 St. Barnabas 醫院完成住院醫師訓練，目前於大溫地區（以本拿比為主）執業。多年來，Dr. Cheng 以親切的服務與良好的溝通深受病患信任。",
      "對於有牙科恐懼或難以配合治療的兒童，Dr. Cheng 擁有豐富的全身麻醉牙科治療經驗，能與麻醉團隊密切合作完成療程。他是 U-Dental 重要的核心成員之一，持續以友善、高品質的服務照顧每一位病患。",
    ],
    related: ["emergency", "crown-and-bridges", "restorations", "dental-cleaning"],
  },
  {
    slug: "dr-yu-ting-liao-dds",
    name: "廖醫師 Dr. Yu-Ting Liao",
    credentials: "DDS",
    photo: "https://u-dental.ca/wp-content/uploads/2018/12/fig7.png",
    specialties: ["顯微鏡牙科", "美學牙科", "Bioclear", "根管治療"],
    summary: "專長顯微鏡輔助美學牙科，擅長修復、根管治療與數位微笑設計。",
    bio: [
      "Dr. Liao 2015 年畢業於台北醫學大學，對美學與修復牙科充滿熱忱。在參與多項國際進修課程後，成為台灣美學牙醫學會與顯微鏡輔助美學牙科學會的會員。",
      "她擅長以顯微鏡輔助進行牙齒修復與根管治療，並具備數位微笑設計的豐富經驗，能在細節中追求精準與美感。對於牙科專業的熱情，讓她持續在臨床上精進與成長。",
    ],
    related: ["root-canal-treatment", "restorations", "cosmetics-and-comprehensive-dentistry"],
  },
  {
    slug: "dr-ivan-kahn-dds",
    name: "Dr. Ivan Kahn",
    credentials: "DDS",
    photo: "/doctors/ivan-kahn.webp",
    specialties: ["美學牙科", "贗復牙科"],
    summary: "1998 年起於加拿大執業，專長軟組織雷射、微笑設計、Invisalign 與 Botox 等現代牙科治療。",
    bio: [
      "Dr. Ivan Kahn 於南非長大，並於約翰尼斯堡完成牙醫專業訓練，自 1998 年起於加拿大執業。他熱愛牙科的各個領域，並持續進修軟組織雷射、美學牙科與微笑設計，曾為 Invisalign 優選提供醫師，並取得 Botox 認證。",
      "Dr. Kahn 也透過多場國際進修課程，深入研究與打鼾及睡眠呼吸中止相關的牙科治療方案。豐富的執業經驗使他能以更全面的視角理解病患的需求與顧慮。",
    ],
    related: ["cosmetics-and-comprehensive-dentistry", "crown-and-bridges", "invisalign", "botox"],
  },
  {
    slug: "dr-suzanne-carlisle-dmd",
    name: "Dr. Suzanne Carlisle",
    credentials: "DMD",
    photo: "/doctors/suzanne-carlisle.webp",
    specialties: ["一般牙科", "口腔腫瘤牙科"],
    summary: "曾多次榮獲 UBC 牙醫學院教學獎的家庭牙醫，每年並擔任 UBC/VGH 住院醫師臨床指導。",
    bio: [
      "Dr. Suzanne Carlisle 是一位資深家庭牙醫，曾多次獲得 UBC 牙醫學院的教學獎項，並每年擔任 UBC/VGH 住院醫師訓練計畫的臨床指導醫師。",
    ],
    related: ["dental-cleaning", "restorations", "crown-and-bridges"],
  },
];

export const TEAM_INTRO_ZH = "我們是一支精通中英雙語的專業牙醫團隊，擁有數十年累積的臨床經驗。U-Dental 將先進的數位牙科、植牙與矯正技術，與專屬手術室的醫療中心級環境結合，為病患帶來高品質的牙科照護。";
