/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermOfServiceRouteImport } from './routes/term-of-service'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyPolicy2RouteImport } from './routes/privacy-policy-2'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceSlugRouteImport } from './routes/service.$slug'
import { Route as DoctorSlugRouteImport } from './routes/doctor.$slug'

const TermOfServiceRoute = TermOfServiceRouteImport.update({
  id: '/term-of-service',
  path: '/term-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicy2Route = PrivacyPolicy2RouteImport.update({
  id: '/privacy-policy-2',
  path: '/privacy-policy-2',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceSlugRoute = ServiceSlugRouteImport.update({
  id: '/service/$slug',
  path: '/service/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorSlugRoute = DoctorSlugRouteImport.update({
  id: '/doctor/$slug',
  path: '/doctor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/privacy-policy-2': typeof PrivacyPolicy2Route
  '/services': typeof ServicesRoute
  '/technology': typeof TechnologyRoute
  '/term-of-service': typeof TermOfServiceRoute
  '/doctor/$slug': typeof DoctorSlugRoute
  '/service/$slug': typeof ServiceSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/privacy-policy-2': typeof PrivacyPolicy2Route
  '/services': typeof ServicesRoute
  '/technology': typeof TechnologyRoute
  '/term-of-service': typeof TermOfServiceRoute
  '/doctor/$slug': typeof DoctorSlugRoute
  '/service/$slug': typeof ServiceSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/privacy-policy-2': typeof PrivacyPolicy2Route
  '/services': typeof ServicesRoute
  '/technology': typeof TechnologyRoute
  '/term-of-service': typeof TermOfServiceRoute
  '/doctor/$slug': typeof DoctorSlugRoute
  '/service/$slug': typeof ServiceSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/privacy-policy'
    | '/privacy-policy-2'
    | '/services'
    | '/technology'
    | '/term-of-service'
    | '/doctor/$slug'
    | '/service/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/privacy-policy'
    | '/privacy-policy-2'
    | '/services'
    | '/technology'
    | '/term-of-service'
    | '/doctor/$slug'
    | '/service/$slug'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/privacy-policy'
    | '/privacy-policy-2'
    | '/services'
    | '/technology'
    | '/term-of-service'
    | '/doctor/$slug'
    | '/service/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactUsRoute: typeof ContactUsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PrivacyPolicy2Route: typeof PrivacyPolicy2Route
  ServicesRoute: typeof ServicesRoute
  TechnologyRoute: typeof TechnologyRoute
  TermOfServiceRoute: typeof TermOfServiceRoute
  DoctorSlugRoute: typeof DoctorSlugRoute
  ServiceSlugRoute: typeof ServiceSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/term-of-service': {
      id: '/term-of-service'
      path: '/term-of-service'
      fullPath: '/term-of-service'
      preLoaderRoute: typeof TermOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy-2': {
      id: '/privacy-policy-2'
      path: '/privacy-policy-2'
      fullPath: '/privacy-policy-2'
      preLoaderRoute: typeof PrivacyPolicy2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$slug': {
      id: '/service/$slug'
      path: '/service/$slug'
      fullPath: '/service/$slug'
      preLoaderRoute: typeof ServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/$slug': {
      id: '/doctor/$slug'
      path: '/doctor/$slug'
      fullPath: '/doctor/$slug'
      preLoaderRoute: typeof DoctorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactUsRoute: ContactUsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PrivacyPolicy2Route: PrivacyPolicy2Route,
  ServicesRoute: ServicesRoute,
  TechnologyRoute: TechnologyRoute,
  TermOfServiceRoute: TermOfServiceRoute,
  DoctorSlugRoute: DoctorSlugRoute,
  ServiceSlugRoute: ServiceSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
