/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermOfServiceRouteImport } from './routes/term-of-service'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyPolicy2RouteImport } from './routes/privacy-policy-2'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZhHantIndexRouteImport } from './routes/zh-hant/index'
import { Route as ZhHantTermOfServiceRouteImport } from './routes/zh-hant/term-of-service'
import { Route as ZhHantTechnologyRouteImport } from './routes/zh-hant/technology'
import { Route as ZhHantServicesRouteImport } from './routes/zh-hant/services'
import { Route as ZhHantPrivacyPolicyRouteImport } from './routes/zh-hant/privacy-policy'
import { Route as ZhHantInsightsRouteImport } from './routes/zh-hant/insights'
import { Route as ZhHantFaqRouteImport } from './routes/zh-hant/faq'
import { Route as ZhHantContactUsRouteImport } from './routes/zh-hant/contact-us'
import { Route as ZhHantAboutUsRouteImport } from './routes/zh-hant/about-us'
import { Route as ServiceSlugRouteImport } from './routes/service.$slug'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as DoctorSlugRouteImport } from './routes/doctor.$slug'
import { Route as ZhHantServiceSlugRouteImport } from './routes/zh-hant/service.$slug'
import { Route as ZhHantInsightsSlugRouteImport } from './routes/zh-hant/insights.$slug'
import { Route as ZhHantDoctorSlugRouteImport } from './routes/zh-hant/doctor.$slug'

const TermOfServiceRoute = TermOfServiceRouteImport.update({
  id: '/term-of-service',
  path: '/term-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicy2Route = PrivacyPolicy2RouteImport.update({
  id: '/privacy-policy-2',
  path: '/privacy-policy-2',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhHantIndexRoute = ZhHantIndexRouteImport.update({
  id: '/zh-hant/',
  path: '/zh-hant/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhHantTermOfServiceRoute = ZhHantTermOfServiceRouteImport.update({
  id: '/zh-hant/term-of-service',
  path: '/zh-hant/term-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhHantTechnologyRoute = ZhHantTechnologyRouteImport.update({
  id: '/zh-hant/technology',
  path: '/zh-hant/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhHantServicesRoute = ZhHantServicesRouteImport.update({
  id: '/zh-hant/services',
  path: '/zh-hant/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhHantPrivacyPolicyRoute = ZhHantPrivacyPolicyRouteImport.update({
  id: '/zh-hant/privacy-policy',
  path: '/zh-hant/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhHantInsightsRoute = ZhHantInsightsRouteImport.update({
  id: '/zh-hant/insights',
  path: '/zh-hant/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhHantFaqRoute = ZhHantFaqRouteImport.update({
  id: '/zh-hant/faq',
  path: '/zh-hant/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhHantContactUsRoute = ZhHantContactUsRouteImport.update({
  id: '/zh-hant/contact-us',
  path: '/zh-hant/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhHantAboutUsRoute = ZhHantAboutUsRouteImport.update({
  id: '/zh-hant/about-us',
  path: '/zh-hant/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceSlugRoute = ServiceSlugRouteImport.update({
  id: '/service/$slug',
  path: '/service/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)
const DoctorSlugRoute = DoctorSlugRouteImport.update({
  id: '/doctor/$slug',
  path: '/doctor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhHantServiceSlugRoute = ZhHantServiceSlugRouteImport.update({
  id: '/zh-hant/service/$slug',
  path: '/zh-hant/service/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhHantInsightsSlugRoute = ZhHantInsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ZhHantInsightsRoute,
} as any)
const ZhHantDoctorSlugRoute = ZhHantDoctorSlugRouteImport.update({
  id: '/zh-hant/doctor/$slug',
  path: '/zh-hant/doctor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/faq': typeof FaqRoute
  '/insights': typeof InsightsRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/privacy-policy-2': typeof PrivacyPolicy2Route
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/technology': typeof TechnologyRoute
  '/term-of-service': typeof TermOfServiceRoute
  '/doctor/$slug': typeof DoctorSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/service/$slug': typeof ServiceSlugRoute
  '/zh-hant/about-us': typeof ZhHantAboutUsRoute
  '/zh-hant/contact-us': typeof ZhHantContactUsRoute
  '/zh-hant/faq': typeof ZhHantFaqRoute
  '/zh-hant/insights': typeof ZhHantInsightsRouteWithChildren
  '/zh-hant/privacy-policy': typeof ZhHantPrivacyPolicyRoute
  '/zh-hant/services': typeof ZhHantServicesRoute
  '/zh-hant/technology': typeof ZhHantTechnologyRoute
  '/zh-hant/term-of-service': typeof ZhHantTermOfServiceRoute
  '/zh-hant/': typeof ZhHantIndexRoute
  '/zh-hant/doctor/$slug': typeof ZhHantDoctorSlugRoute
  '/zh-hant/insights/$slug': typeof ZhHantInsightsSlugRoute
  '/zh-hant/service/$slug': typeof ZhHantServiceSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/faq': typeof FaqRoute
  '/insights': typeof InsightsRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/privacy-policy-2': typeof PrivacyPolicy2Route
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/technology': typeof TechnologyRoute
  '/term-of-service': typeof TermOfServiceRoute
  '/doctor/$slug': typeof DoctorSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/service/$slug': typeof ServiceSlugRoute
  '/zh-hant/about-us': typeof ZhHantAboutUsRoute
  '/zh-hant/contact-us': typeof ZhHantContactUsRoute
  '/zh-hant/faq': typeof ZhHantFaqRoute
  '/zh-hant/insights': typeof ZhHantInsightsRouteWithChildren
  '/zh-hant/privacy-policy': typeof ZhHantPrivacyPolicyRoute
  '/zh-hant/services': typeof ZhHantServicesRoute
  '/zh-hant/technology': typeof ZhHantTechnologyRoute
  '/zh-hant/term-of-service': typeof ZhHantTermOfServiceRoute
  '/zh-hant': typeof ZhHantIndexRoute
  '/zh-hant/doctor/$slug': typeof ZhHantDoctorSlugRoute
  '/zh-hant/insights/$slug': typeof ZhHantInsightsSlugRoute
  '/zh-hant/service/$slug': typeof ZhHantServiceSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/faq': typeof FaqRoute
  '/insights': typeof InsightsRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/privacy-policy-2': typeof PrivacyPolicy2Route
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/technology': typeof TechnologyRoute
  '/term-of-service': typeof TermOfServiceRoute
  '/doctor/$slug': typeof DoctorSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/service/$slug': typeof ServiceSlugRoute
  '/zh-hant/about-us': typeof ZhHantAboutUsRoute
  '/zh-hant/contact-us': typeof ZhHantContactUsRoute
  '/zh-hant/faq': typeof ZhHantFaqRoute
  '/zh-hant/insights': typeof ZhHantInsightsRouteWithChildren
  '/zh-hant/privacy-policy': typeof ZhHantPrivacyPolicyRoute
  '/zh-hant/services': typeof ZhHantServicesRoute
  '/zh-hant/technology': typeof ZhHantTechnologyRoute
  '/zh-hant/term-of-service': typeof ZhHantTermOfServiceRoute
  '/zh-hant/': typeof ZhHantIndexRoute
  '/zh-hant/doctor/$slug': typeof ZhHantDoctorSlugRoute
  '/zh-hant/insights/$slug': typeof ZhHantInsightsSlugRoute
  '/zh-hant/service/$slug': typeof ZhHantServiceSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/faq'
    | '/insights'
    | '/privacy-policy'
    | '/privacy-policy-2'
    | '/services'
    | '/sitemap.xml'
    | '/technology'
    | '/term-of-service'
    | '/doctor/$slug'
    | '/insights/$slug'
    | '/service/$slug'
    | '/zh-hant/about-us'
    | '/zh-hant/contact-us'
    | '/zh-hant/faq'
    | '/zh-hant/insights'
    | '/zh-hant/privacy-policy'
    | '/zh-hant/services'
    | '/zh-hant/technology'
    | '/zh-hant/term-of-service'
    | '/zh-hant/'
    | '/zh-hant/doctor/$slug'
    | '/zh-hant/insights/$slug'
    | '/zh-hant/service/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/faq'
    | '/insights'
    | '/privacy-policy'
    | '/privacy-policy-2'
    | '/services'
    | '/sitemap.xml'
    | '/technology'
    | '/term-of-service'
    | '/doctor/$slug'
    | '/insights/$slug'
    | '/service/$slug'
    | '/zh-hant/about-us'
    | '/zh-hant/contact-us'
    | '/zh-hant/faq'
    | '/zh-hant/insights'
    | '/zh-hant/privacy-policy'
    | '/zh-hant/services'
    | '/zh-hant/technology'
    | '/zh-hant/term-of-service'
    | '/zh-hant'
    | '/zh-hant/doctor/$slug'
    | '/zh-hant/insights/$slug'
    | '/zh-hant/service/$slug'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/faq'
    | '/insights'
    | '/privacy-policy'
    | '/privacy-policy-2'
    | '/services'
    | '/sitemap.xml'
    | '/technology'
    | '/term-of-service'
    | '/doctor/$slug'
    | '/insights/$slug'
    | '/service/$slug'
    | '/zh-hant/about-us'
    | '/zh-hant/contact-us'
    | '/zh-hant/faq'
    | '/zh-hant/insights'
    | '/zh-hant/privacy-policy'
    | '/zh-hant/services'
    | '/zh-hant/technology'
    | '/zh-hant/term-of-service'
    | '/zh-hant/'
    | '/zh-hant/doctor/$slug'
    | '/zh-hant/insights/$slug'
    | '/zh-hant/service/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactUsRoute: typeof ContactUsRoute
  FaqRoute: typeof FaqRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PrivacyPolicy2Route: typeof PrivacyPolicy2Route
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TechnologyRoute: typeof TechnologyRoute
  TermOfServiceRoute: typeof TermOfServiceRoute
  DoctorSlugRoute: typeof DoctorSlugRoute
  ServiceSlugRoute: typeof ServiceSlugRoute
  ZhHantAboutUsRoute: typeof ZhHantAboutUsRoute
  ZhHantContactUsRoute: typeof ZhHantContactUsRoute
  ZhHantFaqRoute: typeof ZhHantFaqRoute
  ZhHantInsightsRoute: typeof ZhHantInsightsRouteWithChildren
  ZhHantPrivacyPolicyRoute: typeof ZhHantPrivacyPolicyRoute
  ZhHantServicesRoute: typeof ZhHantServicesRoute
  ZhHantTechnologyRoute: typeof ZhHantTechnologyRoute
  ZhHantTermOfServiceRoute: typeof ZhHantTermOfServiceRoute
  ZhHantIndexRoute: typeof ZhHantIndexRoute
  ZhHantDoctorSlugRoute: typeof ZhHantDoctorSlugRoute
  ZhHantServiceSlugRoute: typeof ZhHantServiceSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/term-of-service': {
      id: '/term-of-service'
      path: '/term-of-service'
      fullPath: '/term-of-service'
      preLoaderRoute: typeof TermOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy-2': {
      id: '/privacy-policy-2'
      path: '/privacy-policy-2'
      fullPath: '/privacy-policy-2'
      preLoaderRoute: typeof PrivacyPolicy2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-hant/': {
      id: '/zh-hant/'
      path: '/zh-hant'
      fullPath: '/zh-hant/'
      preLoaderRoute: typeof ZhHantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-hant/term-of-service': {
      id: '/zh-hant/term-of-service'
      path: '/zh-hant/term-of-service'
      fullPath: '/zh-hant/term-of-service'
      preLoaderRoute: typeof ZhHantTermOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-hant/technology': {
      id: '/zh-hant/technology'
      path: '/zh-hant/technology'
      fullPath: '/zh-hant/technology'
      preLoaderRoute: typeof ZhHantTechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-hant/services': {
      id: '/zh-hant/services'
      path: '/zh-hant/services'
      fullPath: '/zh-hant/services'
      preLoaderRoute: typeof ZhHantServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-hant/privacy-policy': {
      id: '/zh-hant/privacy-policy'
      path: '/zh-hant/privacy-policy'
      fullPath: '/zh-hant/privacy-policy'
      preLoaderRoute: typeof ZhHantPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-hant/insights': {
      id: '/zh-hant/insights'
      path: '/zh-hant/insights'
      fullPath: '/zh-hant/insights'
      preLoaderRoute: typeof ZhHantInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-hant/faq': {
      id: '/zh-hant/faq'
      path: '/zh-hant/faq'
      fullPath: '/zh-hant/faq'
      preLoaderRoute: typeof ZhHantFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-hant/contact-us': {
      id: '/zh-hant/contact-us'
      path: '/zh-hant/contact-us'
      fullPath: '/zh-hant/contact-us'
      preLoaderRoute: typeof ZhHantContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-hant/about-us': {
      id: '/zh-hant/about-us'
      path: '/zh-hant/about-us'
      fullPath: '/zh-hant/about-us'
      preLoaderRoute: typeof ZhHantAboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$slug': {
      id: '/service/$slug'
      path: '/service/$slug'
      fullPath: '/service/$slug'
      preLoaderRoute: typeof ServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/doctor/$slug': {
      id: '/doctor/$slug'
      path: '/doctor/$slug'
      fullPath: '/doctor/$slug'
      preLoaderRoute: typeof DoctorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-hant/service/$slug': {
      id: '/zh-hant/service/$slug'
      path: '/zh-hant/service/$slug'
      fullPath: '/zh-hant/service/$slug'
      preLoaderRoute: typeof ZhHantServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh-hant/insights/$slug': {
      id: '/zh-hant/insights/$slug'
      path: '/$slug'
      fullPath: '/zh-hant/insights/$slug'
      preLoaderRoute: typeof ZhHantInsightsSlugRouteImport
      parentRoute: typeof ZhHantInsightsRoute
    }
    '/zh-hant/doctor/$slug': {
      id: '/zh-hant/doctor/$slug'
      path: '/zh-hant/doctor/$slug'
      fullPath: '/zh-hant/doctor/$slug'
      preLoaderRoute: typeof ZhHantDoctorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

interface ZhHantInsightsRouteChildren {
  ZhHantInsightsSlugRoute: typeof ZhHantInsightsSlugRoute
}

const ZhHantInsightsRouteChildren: ZhHantInsightsRouteChildren = {
  ZhHantInsightsSlugRoute: ZhHantInsightsSlugRoute,
}

const ZhHantInsightsRouteWithChildren = ZhHantInsightsRoute._addFileChildren(
  ZhHantInsightsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactUsRoute: ContactUsRoute,
  FaqRoute: FaqRoute,
  InsightsRoute: InsightsRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PrivacyPolicy2Route: PrivacyPolicy2Route,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TechnologyRoute: TechnologyRoute,
  TermOfServiceRoute: TermOfServiceRoute,
  DoctorSlugRoute: DoctorSlugRoute,
  ServiceSlugRoute: ServiceSlugRoute,
  ZhHantAboutUsRoute: ZhHantAboutUsRoute,
  ZhHantContactUsRoute: ZhHantContactUsRoute,
  ZhHantFaqRoute: ZhHantFaqRoute,
  ZhHantInsightsRoute: ZhHantInsightsRouteWithChildren,
  ZhHantPrivacyPolicyRoute: ZhHantPrivacyPolicyRoute,
  ZhHantServicesRoute: ZhHantServicesRoute,
  ZhHantTechnologyRoute: ZhHantTechnologyRoute,
  ZhHantTermOfServiceRoute: ZhHantTermOfServiceRoute,
  ZhHantIndexRoute: ZhHantIndexRoute,
  ZhHantDoctorSlugRoute: ZhHantDoctorSlugRoute,
  ZhHantServiceSlugRoute: ZhHantServiceSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
